title: The Cyclotron Project
author:
  name: Reed Upson & Ray Anchordoquy
  email: ranchordo@gmail.com
description: The ongoing quest to bring garage-grown, locally produced antimatter to a random basement near you.
repository: thecyclotronproject/thecyclotronproject.github.io

url: https://thecyclotronproject.github.io

permalink: pretty

# Build settings
remote_theme: jekyll/minima

show_excerpts: false
# Hey Reed, add pages here, you need to create markdown files for each one. It's YAML, so just follow the format.
header_pages:
  - test01.md
  - test02.md
  - test03.md
plugins:
  - jekyll-feed
  - jekyll-remote-theme
minima:
  skin: dark
